### ISSUE TITLE
Código não compila sem hdf5=1 paralelo=1

### ISSUE THREAD

**Issue by lvella** [MFLab-AMR3D/AMR3D#1]
Ou a necessidade de se usar `hdf5=1 paralelo=1` no comando `make` deve ser removida, ou o código deve compilar com sem essas flags.

Idealmente, como o software é mais usado com essas opções do que sem, mesmo que sejam opcionais, elas deveriam ser habilitadas por padrãos, com a opção de serem desabilitadas usando alguma flag.

**Comment by faelromelo** [comment]
Concordo.

**Comment by pedro-ricardo** [comment]
Concordo plenamente.

**Comment by pedro-ricardo** [comment]
Corrigido! Como o código não funciona sem essas flags elas estão adicionadas por default no Makefile.
