### ISSUE TITLE
problema com a divisão de processos ao longo de uma direção periódica

### ISSUE THREAD

**Issue by aeliasMFlab** [MFLab-AMR3D/AMR3D#11]
Problema ao tentar rodar um caso com 4 processos ao longo da direção periódica. O código entra na função **transfer_patches(headlev,1, ltop)** e não consegue sair.

O input em anexo se refere a um paralelepípedo com 8 x 8 x 32 células no nível base, dividido em 1 x 1 x 4 processos. Todas as bc's são dirichlet.
[input.txt](https://github.com/MFLab-AMR3D/AMR3D/files/1634912/input.txt)

main.f90 > **transfer_patches** 
```
   if (n_proc>1) then
        !! Share the patches (among neighbour processors) 
        !that are next to the local(processor) boundaries
        if(.not.virtual)then
        call transfer_patches(headlev,lbot, ltop)
        else
        call transfer_patches(headlev,1, ltop)
        end if
     end if
```

**Comment by pedro-ricardo** [comment]
O problema estava na linha **363** do arquivo **src_par/topology.f90**. A variável do `if` deveria ser `gkkn` e não `giin` como estava

Log da alteração no Git-master
```diff
  if (z_periodic==1) then
        if (iz(1)<gkk1) iz(1) = nint((gb3-ga3)/dz)
-       if (iz(ncells_z+2*layer)>giin) iz(ncells_z+2*layer) = int((ga3)/dz)+1
+       if (iz(ncells_z+2*layer)>gkkn) iz(ncells_z+2*layer) = int((ga3)/dz)+1
  end if
```
Problema resolvido pela Millena, a alteração já esta no **master**.
