### ISSUE TITLE
Não existe passo de tempo 1 sendo impresso.

### ISSUE THREAD

**Issue by lvella** [MFLab-AMR3D/AMR3D#2]
Se eu mandar imprimir a todo passo de tempo, o primeiro passo impresso é o 0, e o próximo é o 2:

```
ns_output_ct.000000000.hdf5
ns_output_ct.000000002.hdf5
...
```

**Comment by vitorvilela** [comment]
Vella, 

apesar de imprimir forçosamente ct=0 no primeiro print [post_proc_output(headlev, **0**, ns_vu_0, ns_vv_0, ns_vw_0, ns_pres, ns_visc)], ct=1 corresponde a condição inicial [linha 185]. ct=2 é passo de tempo (futuro) correspondente à chamada de call starting_un_euler().

**Comment by lvella** [comment]
Meu problema é semântico: tem o zero, pula o 1, depois tem do 2 em diante. O zero não pode ser chamado de 1 no arquivo para a saída ficar contínua?

**Comment by faelromelo** [comment]
Pode sim mudar de 0 para 1, porém nem sempre será salvo todo passo de tempo, então se for de 50 em 50 sera impresso 0, 2, 50, 100, 150 ....
