### ISSUE TITLE
Seleção de array incorreta na interpolação da saída em HDF5

### ISSUE THREAD

**Issue by lvella** [MFLab-AMR3D/AMR3D#3]
Na linha 1215 do arquivo `print_hdf5.f90` (e em vários comentários no mesmo arquivo que contêm o mesmo código) a seleção do vetor p está incorreta, sendo o intervalo da segunda coordenada `igy-1:igy+ny-1-1`, enquanto deveria ser `igy-1:igy+ny-1`.

**Comment by pedro-ricardo** [comment]
Corrigido!
