### ISSUE TITLE
Compilação padrão não otimizada

### ISSUE THREAD

**Issue by lvella** [MFLab-AMR3D/AMR3D#4]
Quando AMR3D é compilado com `make paralelo=1 hdf5=1`, a compilação é feita com a opção `-O1` e sem a opção `-g`. Isso significa que o programa gerado não é nem muito otimizado (o ideal para rodar casos é no mínimo `-O3`) e nem adequado para debug (que necessita de `-g`).

A configuração padrão de compilação deveria incluir `-O3`, e até que se prove que `-g` afeta a performance, ele deve ser incluido também, já que facilita o debug.

**Comment by pedro-ricardo** [comment]
Corrigido! O Makefile atual incorpora as mudanças sugeridas.
